version: '3'

services:
  postgres:
    container_name: transactions-pg
    restart: always
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apiTransactionDB
    volumes:
      - postgresql_data:/bitnami/postgresql
  app:
    build: .
    container_name: apiTransactions
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: "host"
volumes:
  postgresql_data:
   