version: '3'

services:
  postgres:
    container_name: transactions-pg
    restart: always
    image: postgres
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: transactionDB
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  node:
    container_name: apiTransactions
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    expose:
      - "3333"
    ports:
      - 3333:3333
    depends_on:
      - postgres
    volumes:
     - ./:/home/node/app
